### ISSUE TITLE
proxy doesn't work as parameter in session request

### ISSUE THREAD

**Issue by cctse** [levigross/grequests#56] opened 2017-09-06 02:36 UTC
working well as follow:
```
var ourl = "http://baidu.com"
prox,_ := url.Parse("http://219.135.164.245:3128")
fmt.Println("prox:", prox)

session := grequests.NewSession(&grequests.RequestOptions{
	Proxies:map[string]*url.URL{prox.Scheme:prox},
})
rsp,err := session.Get(ourl, nil)

fmt.Println(err, rsp.String())
```

not working as follow:
```
var ourl = "http://baidu.com"
prox,_ := url.Parse("http://219.135.164.245:3128")
fmt.Println("prox:", prox)

session := grequests.NewSession(nil)
rsp,err := session.Get(ourl, &grequests.RequestOptions{
	Proxies:map[string]*url.URL{prox.Scheme:prox},
})

fmt.Println(err, rsp.String())
```

**Comment by cctse** [comment] 2017-09-06 03:00
this not working too
```
prox,_ := url.Parse("http://219.135.164.245:3128")
fmt.Println("prox:", prox)

session := grequests.NewSession(nil)
session.RequestOptions.Proxies = map[string]*url.URL{prox.Scheme:prox}
rsp,err := session.Get(ourl, nil)

fmt.Println(err, rsp.String())
```

**Comment by icongshi** [comment] 2018-07-17 00:55
this is not a bug. Could close this issue.

**Closed** 2018-07-17 01:41 UTC
